# PowerShell.exe -File <FileName> -ExecutionPolicy Bypass 
choco install 7zip
choco install ditto
choco install docker-desktop
choco install fira
choco install flameshot
choco install googlechrome
choco install mactype
choco install microsoft-teams
choco install microsoft-windows-terminal
choco install modernflyouts
choco install neovim
choco install notepadplusplus
choco install notion
choco install okular
choco install powershell
choco install powertoys
choco install telegram
choco install vscode
choco install win32yank
choco install nerd-fonts-hack
choco install nerd-fonts-cascadiacode
choco install nerd-fonts-codenewroman
