##PowerShell.exe -File <FileName> -ExecutionPolicy Bypass
scoop install aria2
scoop install bat
scoop install curl
scoop install fd
scoop install fnm
scoop install fzf
scoop install gawk
scoop install lsd
scoop install ripgrep
scoop install sudo
scoop install telnet
scoop install time
scoop install tldr
scoop install tree-sitter
scoop install wget
scoop install zip
scoop install zoxide
scoop install sort-uniq-wc
scoop install psfzf
scoop install psreadline
scoop install vim
scoop install vlc
