##PowerShell.exe -File <FileName> -ExecutionPolicy Bypass
scoop install bat
scoop install curl
scoop install fd
scoop install fnm
scoop install fzf
scoop install gawk
scoop install lsd
scoop install make
scoop install mingw
scoop install tldr
scoop install wget
scoop install zip
scoop install zoxide
scoop install sort-uniq-wc
scoop install psfzf
scoop install psreadline
scoop install ripgrep
scoop install starship
scoop install sudo
scoop install vim
scoop install vlc
scoop install https://raw.githubusercontent.com/lukesampson/shimexe/master/scoop/shim.json
