##PowerShell.exe -File <FileName> -ExecutionPolicy Bypass
scoop install bat
scoop install fd
scoop install fzf
scoop install https://raw.githubusercontent.com/lukesampson/shimexe/master/scoop/shim.json
scoop install lsd
scoop install make
scoop install mingw
scoop install nerd-fonts/CodeNewRoman-NF-Mono
scoop install nerd-fonts/Hack-NF-Mono
scoop install nodejs
scoop install psfzf
scoop install psreadline
scoop install ripgrep
scoop install sort-uniq-wc
scoop install starship
scoop install sudo
scoop install tldr
scoop install vim
scoop install vlc
scoop install wget
scoop install zoxide
